### ISSUE TITLE
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROOT_APPENDER] - Failed to create parent directories for [/data123/projects/logs/zuihou-authority-server/root.log]

### ISSUE THREAD

**Issue by zuihou** [zuihou/lamp-cloud#18]
**版本信息：**
- 源码版本：2.5.0
- MySQL： 5.7.9
- Nacos：1.2.1
- 操作系统： Mac 或者 Linux

**问题描述：**
使用IDEA 或者 JAR 启动项目时，报错：
```
[zuihou-authority-server:0000::] 2020-09-03 14:09:06.714:[ERROR] [78530] [] [main:11027] [org.springframework.boot.SpringApplication.reportFailure:826] Application run failed

java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROOT_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/root.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[ROOT_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/root.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/root.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[PROJECT_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/project.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[PROJECT_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/project.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/project.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[THIRD_PARTY_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/third_party.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[THIRD_PARTY_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/third_party.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/third_party.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SERVICE_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/service.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[SERVICE_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/service.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/service.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[POINT_LOG_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/point.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[POINT_LOG_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/point.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/point.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[CONTROLLER_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/controller.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[CONTROLLER_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/controller.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/controller.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DAO_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/dao.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[DAO_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/dao.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/dao.log (No such file or directory)
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[EXCEPTION_APPENDER] - Failed to create parent directories for [/data/projects/logs/zuihou-authority-server/exception.log]
ERROR in ch.qos.logback.core.rolling.RollingFileAppender[EXCEPTION_APPENDER] - openFile(/data/projects/logs/zuihou-authority-server/exception.log,true) call failed. java.io.FileNotFoundException: /data/projects/logs/zuihou-authority-server/exception.log (No such file or directory)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:288)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:212)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:117)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:74)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.github.zuihou.AuthorityApplication.main(AuthorityApplication.java:38)
```

# 支持一下:
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
这个问题一般只会出现在Mac 和Linux 系统上，报错的意思是：
无法为创建日志文件：/data/projects/logs/zuihou-authority-server/root.log 等。

解决方案1：  src/main/filters/config-xxx.properties 文件中的 logging.file.path 路径，改成服务器中当前用户有权限访问，并且正式存在的路径
```
# 日志存储路径
logging.file.path=/data/projects/logs
```
解决方案2： 在你的电脑或者服务器上 手动创建 /data/projects/logs 目录，并授权给当前启用项目的用户
```
# 伪代码
mkdir -p /data/projects/logs
chown -R 用户:组 /data  
```



画外音：
日志文件为什么要放在 /data/projects 目录，而非相对路径？
原因1：正式环境服务器磁盘通常是外挂到某个目录的，系统目录通常空间分销，所以需要将日志等文件指定存放在挂载的目录。 原因2：开发环境将所有系统日志存放在一起，并按项目名区分，便于后期批量清理日志文件，不用在每个项目的根路径存储日志文件。
